import jsPDF from "jspdf";

export async function generateDamageReportPdf({
  report,
  resultImage,
  severity,
  fileName,
}: {
  report: any;
  resultImage: string | null;
  severity: string;
  fileName: string;
}) {
  const pdf = new jsPDF("p", "mm", "a4");

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  let y = 20;

  // =========================
  // TITLE
  // =========================

  pdf.setFontSize(22);
  pdf.setFont("helvetica", "bold");
  pdf.text("Car Damage Assessment Report", 20, y);

  y += 10;

  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");
  pdf.text("Generated by CarDD AI", 20, y);

  y += 12;

  // =========================
  // ANNOTATED IMAGE
  // =========================

  if (resultImage) {
    const image = new Image();

    await new Promise<void>((resolve, reject) => {
      image.onload = () => resolve();
      image.onerror = reject;
      image.src = resultImage;
    });

    const maxWidth = pageWidth - 40;
    const maxHeight = 90;

    let imgWidth = image.naturalWidth;
    let imgHeight = image.naturalHeight;

    const ratio = Math.min(maxWidth / imgWidth, maxHeight / imgHeight);

    imgWidth *= ratio;
    imgHeight *= ratio;

    const x = (pageWidth - imgWidth) / 2;

    pdf.addImage(image, "JPEG", x, y, imgWidth, imgHeight);

    y += imgHeight + 12;
  }

  // =========================
  // OVERALL SEVERITY
  // =========================

  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text("Overall Severity", 20, y);

  y += 8;

  pdf.setFontSize(12);
  pdf.setFont("helvetica", "normal");
  pdf.text(severity || "Unknown", 20, y);

  y += 12;

  // =========================
  // DAMAGE ASSESSMENT
  // =========================

  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text("Damage Assessment", 20, y);

  y += 9;

  for (const damage of report.damage_assessment || []) {
    if (y > pageHeight - 45) {
      pdf.addPage();
      y = 20;
    }

    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");

    pdf.text(damage.damage_type, 20, y);

    y += 6;

    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");

    pdf.text(`Location: ${damage.location_on_vehicle}`, 20, y);

    y += 5;

    pdf.text(`Severity: ${damage.severity}`, 20, y);

    y += 6;

    const descriptionLines = pdf.splitTextToSize(
      damage.description,
      pageWidth - 40,
    );

    pdf.text(descriptionLines, 20, y);

    y += descriptionLines.length * 5 + 8;
  }

  // =========================
  // REPAIR STEPS
  // =========================

  if (y > pageHeight - 50) {
    pdf.addPage();
    y = 20;
  }

  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text("Repair Steps", 20, y);

  y += 9;

  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");

  for (let i = 0; i < (report.repair_steps || []).length; i++) {
    const step = report.repair_steps[i];

    const lines = pdf.splitTextToSize(`${i + 1}. ${step}`, pageWidth - 40);

    if (y + lines.length * 5 > pageHeight - 20) {
      pdf.addPage();
      y = 20;
    }

    pdf.text(lines, 20, y);

    y += lines.length * 5 + 3;
  }

  // =========================
  // TOOLS & EQUIPMENT
  // =========================

  if (y > pageHeight - 50) {
    pdf.addPage();
    y = 20;
  }

  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text("Tools & Equipment", 20, y);

  y += 9;

  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");

  for (const tool of report.tools_and_equipment_needed || []) {
    pdf.text(`• ${tool}`, 20, y);
    y += 6;
  }

  y += 5;

  // =========================
  // ESTIMATED COST
  // =========================

  if (y > pageHeight - 60) {
    pdf.addPage();
    y = 20;
  }

  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text("Estimated Cost", 20, y);

  y += 9;

  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");

  pdf.text(`Repair Time: ${report.estimated_repair_time_hours} hours`, 20, y);

  y += 6;

  pdf.text(
    `Technician Service: ${report.technician_service_cost_egp?.min?.toLocaleString()} – ${report.technician_service_cost_egp?.max?.toLocaleString()} EGP`,
    20,
    y,
  );

  y += 6;

  pdf.text(
    `Parts & Equipment: ${report.equipment_and_parts_cost_egp?.min?.toLocaleString()} – ${report.equipment_and_parts_cost_egp?.max?.toLocaleString()} EGP`,
    20,
    y,
  );

  y += 8;

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(13);

  pdf.text(
    `Total Estimated Cost: ${report.total_estimated_cost_egp?.min?.toLocaleString()} – ${report.total_estimated_cost_egp?.max?.toLocaleString()} EGP`,
    20,
    y,
  );

  y += 12;

  // =========================
  // NOTES
  // =========================

  if (report.notes) {
    if (y > pageHeight - 45) {
      pdf.addPage();
      y = 20;
    }

    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("Notes", 20, y);

    y += 8;

    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");

    const noteLines = pdf.splitTextToSize(report.notes, pageWidth - 40);

    pdf.text(noteLines, 20, y);
  }

  // =========================
  // SAVE
  // =========================

  pdf.save(`CarDD-Damage-Report-${fileName || "vehicle"}.pdf`);
}
